services:
  # Backend API with FreeCAD and SQLite
  - type: web
    name: plastic-configurator-backend
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: False
      - key: CORS_ORIGINS
        value: https://plastic-configurator-frontend.onrender.com
      - key: STORAGE_TYPE
        value: local
      - key: STORAGE_PATH
        value: /app/storage/cad_files
      - key: FREECAD_PATH
        value: /usr/lib/freecad-python3/lib
      - key: FREECAD_PYTHON
        value: /usr/bin/freecadcmd
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: backend-data
      mountPath: /app
      sizeGB: 1

  # Frontend
  - type: web
    name: plastic-configurator-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://plastic-configurator-backend.onrender.com
    autoDeploy: true

